[package]
name = "cryptography"
version = "0.1.0"
edition = "2024"

[dependencies]
chacha20poly1305 = "0.10.1"
x25519-dalek = { version = "2.0.1", features = ["static_secrets"] }
hkdf = "0.12.4"
sha2 = "0.10.9"
